# 构建环境
FROM python:3.12-slim

# 设置工作目录
WORKDIR /app

RUN pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple isort[colors]==7.0.0

# 清理环境
RUN rm -rf /var/lib/apt/lists/* /root/.cache/pip