# 构建环境
FROM python:3.12-slim

# 设置工作目录
WORKDIR /callback

# 复制依赖文件并安装
COPY ./callback/requirements.txt .

RUN pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

# 清理环境
RUN rm -rf /var/lib/apt/lists/* /root/.cache/pip

# 环境变量
ENV FLASK_APP=run.py

EXPOSE 8669

# 使用 gunicorn 启动 Flask（加载 run.py 中的 app）
CMD ["gunicorn", "-w", "8", "-b", "0.0.0.0:8669", "run:app"]