// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/knowledgebase-qa-service/knowledgebase-qa-service.proto

package knowledgebase_qa_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeBaseQAService_CreateQAPair_FullMethodName       = "/knowledgebase_qa_service.KnowledgeBaseQAService/CreateQAPair"
	KnowledgeBaseQAService_UpdateQAPair_FullMethodName       = "/knowledgebase_qa_service.KnowledgeBaseQAService/UpdateQAPair"
	KnowledgeBaseQAService_UpdateQAPairSwitch_FullMethodName = "/knowledgebase_qa_service.KnowledgeBaseQAService/UpdateQAPairSwitch"
	KnowledgeBaseQAService_DeleteQAPair_FullMethodName       = "/knowledgebase_qa_service.KnowledgeBaseQAService/DeleteQAPair"
	KnowledgeBaseQAService_GetQAPairInfo_FullMethodName      = "/knowledgebase_qa_service.KnowledgeBaseQAService/GetQAPairInfo"
	KnowledgeBaseQAService_GetQAPairList_FullMethodName      = "/knowledgebase_qa_service.KnowledgeBaseQAService/GetQAPairList"
	KnowledgeBaseQAService_ImportQAPair_FullMethodName       = "/knowledgebase_qa_service.KnowledgeBaseQAService/ImportQAPair"
	KnowledgeBaseQAService_GetQAImportTip_FullMethodName     = "/knowledgebase_qa_service.KnowledgeBaseQAService/GetQAImportTip"
	KnowledgeBaseQAService_ExportQAPair_FullMethodName       = "/knowledgebase_qa_service.KnowledgeBaseQAService/ExportQAPair"
	KnowledgeBaseQAService_KnowledgeQAHit_FullMethodName     = "/knowledgebase_qa_service.KnowledgeBaseQAService/KnowledgeQAHit"
)

// KnowledgeBaseQAServiceClient is the client API for KnowledgeBaseQAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeBaseQAServiceClient interface {
	// 新建问答对
	CreateQAPair(ctx context.Context, in *CreateQAPairReq, opts ...grpc.CallOption) (*CreateQAPairResp, error)
	// 更新问答对
	UpdateQAPair(ctx context.Context, in *UpdateQAPairReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 启停问答对
	UpdateQAPairSwitch(ctx context.Context, in *UpdateQAPairSwitchReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除问答对
	DeleteQAPair(ctx context.Context, in *DeleteQAPairReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取问答对详情
	GetQAPairInfo(ctx context.Context, in *GetQAPairInfoReq, opts ...grpc.CallOption) (*QAPairInfo, error)
	// 获取问答对列表
	GetQAPairList(ctx context.Context, in *GetQAPairListReq, opts ...grpc.CallOption) (*GetQAPairListResp, error)
	// 导入文档
	ImportQAPair(ctx context.Context, in *ImportQAPairReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取问答库异步上传任务提示
	GetQAImportTip(ctx context.Context, in *QAImportTipReq, opts ...grpc.CallOption) (*QAImportTipResp, error)
	// 导出文档
	ExportQAPair(ctx context.Context, in *ExportQAPairReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 问答库命中测试
	KnowledgeQAHit(ctx context.Context, in *KnowledgeQAHitReq, opts ...grpc.CallOption) (*KnowledgeQAHitResp, error)
}

type knowledgeBaseQAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeBaseQAServiceClient(cc grpc.ClientConnInterface) KnowledgeBaseQAServiceClient {
	return &knowledgeBaseQAServiceClient{cc}
}

func (c *knowledgeBaseQAServiceClient) CreateQAPair(ctx context.Context, in *CreateQAPairReq, opts ...grpc.CallOption) (*CreateQAPairResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQAPairResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseQAService_CreateQAPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseQAServiceClient) UpdateQAPair(ctx context.Context, in *UpdateQAPairReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseQAService_UpdateQAPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseQAServiceClient) UpdateQAPairSwitch(ctx context.Context, in *UpdateQAPairSwitchReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseQAService_UpdateQAPairSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseQAServiceClient) DeleteQAPair(ctx context.Context, in *DeleteQAPairReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseQAService_DeleteQAPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseQAServiceClient) GetQAPairInfo(ctx context.Context, in *GetQAPairInfoReq, opts ...grpc.CallOption) (*QAPairInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QAPairInfo)
	err := c.cc.Invoke(ctx, KnowledgeBaseQAService_GetQAPairInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseQAServiceClient) GetQAPairList(ctx context.Context, in *GetQAPairListReq, opts ...grpc.CallOption) (*GetQAPairListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQAPairListResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseQAService_GetQAPairList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseQAServiceClient) ImportQAPair(ctx context.Context, in *ImportQAPairReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseQAService_ImportQAPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseQAServiceClient) GetQAImportTip(ctx context.Context, in *QAImportTipReq, opts ...grpc.CallOption) (*QAImportTipResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QAImportTipResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseQAService_GetQAImportTip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseQAServiceClient) ExportQAPair(ctx context.Context, in *ExportQAPairReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseQAService_ExportQAPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseQAServiceClient) KnowledgeQAHit(ctx context.Context, in *KnowledgeQAHitReq, opts ...grpc.CallOption) (*KnowledgeQAHitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeQAHitResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseQAService_KnowledgeQAHit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeBaseQAServiceServer is the server API for KnowledgeBaseQAService service.
// All implementations must embed UnimplementedKnowledgeBaseQAServiceServer
// for forward compatibility.
type KnowledgeBaseQAServiceServer interface {
	// 新建问答对
	CreateQAPair(context.Context, *CreateQAPairReq) (*CreateQAPairResp, error)
	// 更新问答对
	UpdateQAPair(context.Context, *UpdateQAPairReq) (*emptypb.Empty, error)
	// 启停问答对
	UpdateQAPairSwitch(context.Context, *UpdateQAPairSwitchReq) (*emptypb.Empty, error)
	// 删除问答对
	DeleteQAPair(context.Context, *DeleteQAPairReq) (*emptypb.Empty, error)
	// 获取问答对详情
	GetQAPairInfo(context.Context, *GetQAPairInfoReq) (*QAPairInfo, error)
	// 获取问答对列表
	GetQAPairList(context.Context, *GetQAPairListReq) (*GetQAPairListResp, error)
	// 导入文档
	ImportQAPair(context.Context, *ImportQAPairReq) (*emptypb.Empty, error)
	// 获取问答库异步上传任务提示
	GetQAImportTip(context.Context, *QAImportTipReq) (*QAImportTipResp, error)
	// 导出文档
	ExportQAPair(context.Context, *ExportQAPairReq) (*emptypb.Empty, error)
	// 问答库命中测试
	KnowledgeQAHit(context.Context, *KnowledgeQAHitReq) (*KnowledgeQAHitResp, error)
	mustEmbedUnimplementedKnowledgeBaseQAServiceServer()
}

// UnimplementedKnowledgeBaseQAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeBaseQAServiceServer struct{}

func (UnimplementedKnowledgeBaseQAServiceServer) CreateQAPair(context.Context, *CreateQAPairReq) (*CreateQAPairResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQAPair not implemented")
}
func (UnimplementedKnowledgeBaseQAServiceServer) UpdateQAPair(context.Context, *UpdateQAPairReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQAPair not implemented")
}
func (UnimplementedKnowledgeBaseQAServiceServer) UpdateQAPairSwitch(context.Context, *UpdateQAPairSwitchReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQAPairSwitch not implemented")
}
func (UnimplementedKnowledgeBaseQAServiceServer) DeleteQAPair(context.Context, *DeleteQAPairReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQAPair not implemented")
}
func (UnimplementedKnowledgeBaseQAServiceServer) GetQAPairInfo(context.Context, *GetQAPairInfoReq) (*QAPairInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQAPairInfo not implemented")
}
func (UnimplementedKnowledgeBaseQAServiceServer) GetQAPairList(context.Context, *GetQAPairListReq) (*GetQAPairListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQAPairList not implemented")
}
func (UnimplementedKnowledgeBaseQAServiceServer) ImportQAPair(context.Context, *ImportQAPairReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportQAPair not implemented")
}
func (UnimplementedKnowledgeBaseQAServiceServer) GetQAImportTip(context.Context, *QAImportTipReq) (*QAImportTipResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQAImportTip not implemented")
}
func (UnimplementedKnowledgeBaseQAServiceServer) ExportQAPair(context.Context, *ExportQAPairReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportQAPair not implemented")
}
func (UnimplementedKnowledgeBaseQAServiceServer) KnowledgeQAHit(context.Context, *KnowledgeQAHitReq) (*KnowledgeQAHitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnowledgeQAHit not implemented")
}
func (UnimplementedKnowledgeBaseQAServiceServer) mustEmbedUnimplementedKnowledgeBaseQAServiceServer() {
}
func (UnimplementedKnowledgeBaseQAServiceServer) testEmbeddedByValue() {}

// UnsafeKnowledgeBaseQAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeBaseQAServiceServer will
// result in compilation errors.
type UnsafeKnowledgeBaseQAServiceServer interface {
	mustEmbedUnimplementedKnowledgeBaseQAServiceServer()
}

func RegisterKnowledgeBaseQAServiceServer(s grpc.ServiceRegistrar, srv KnowledgeBaseQAServiceServer) {
	// If the following call pancis, it indicates UnimplementedKnowledgeBaseQAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeBaseQAService_ServiceDesc, srv)
}

func _KnowledgeBaseQAService_CreateQAPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQAPairReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseQAServiceServer).CreateQAPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseQAService_CreateQAPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseQAServiceServer).CreateQAPair(ctx, req.(*CreateQAPairReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseQAService_UpdateQAPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQAPairReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseQAServiceServer).UpdateQAPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseQAService_UpdateQAPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseQAServiceServer).UpdateQAPair(ctx, req.(*UpdateQAPairReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseQAService_UpdateQAPairSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQAPairSwitchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseQAServiceServer).UpdateQAPairSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseQAService_UpdateQAPairSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseQAServiceServer).UpdateQAPairSwitch(ctx, req.(*UpdateQAPairSwitchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseQAService_DeleteQAPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQAPairReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseQAServiceServer).DeleteQAPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseQAService_DeleteQAPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseQAServiceServer).DeleteQAPair(ctx, req.(*DeleteQAPairReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseQAService_GetQAPairInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQAPairInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseQAServiceServer).GetQAPairInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseQAService_GetQAPairInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseQAServiceServer).GetQAPairInfo(ctx, req.(*GetQAPairInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseQAService_GetQAPairList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQAPairListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseQAServiceServer).GetQAPairList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseQAService_GetQAPairList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseQAServiceServer).GetQAPairList(ctx, req.(*GetQAPairListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseQAService_ImportQAPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportQAPairReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseQAServiceServer).ImportQAPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseQAService_ImportQAPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseQAServiceServer).ImportQAPair(ctx, req.(*ImportQAPairReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseQAService_GetQAImportTip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QAImportTipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseQAServiceServer).GetQAImportTip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseQAService_GetQAImportTip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseQAServiceServer).GetQAImportTip(ctx, req.(*QAImportTipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseQAService_ExportQAPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportQAPairReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseQAServiceServer).ExportQAPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseQAService_ExportQAPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseQAServiceServer).ExportQAPair(ctx, req.(*ExportQAPairReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseQAService_KnowledgeQAHit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeQAHitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseQAServiceServer).KnowledgeQAHit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseQAService_KnowledgeQAHit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseQAServiceServer).KnowledgeQAHit(ctx, req.(*KnowledgeQAHitReq))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeBaseQAService_ServiceDesc is the grpc.ServiceDesc for KnowledgeBaseQAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeBaseQAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledgebase_qa_service.KnowledgeBaseQAService",
	HandlerType: (*KnowledgeBaseQAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQAPair",
			Handler:    _KnowledgeBaseQAService_CreateQAPair_Handler,
		},
		{
			MethodName: "UpdateQAPair",
			Handler:    _KnowledgeBaseQAService_UpdateQAPair_Handler,
		},
		{
			MethodName: "UpdateQAPairSwitch",
			Handler:    _KnowledgeBaseQAService_UpdateQAPairSwitch_Handler,
		},
		{
			MethodName: "DeleteQAPair",
			Handler:    _KnowledgeBaseQAService_DeleteQAPair_Handler,
		},
		{
			MethodName: "GetQAPairInfo",
			Handler:    _KnowledgeBaseQAService_GetQAPairInfo_Handler,
		},
		{
			MethodName: "GetQAPairList",
			Handler:    _KnowledgeBaseQAService_GetQAPairList_Handler,
		},
		{
			MethodName: "ImportQAPair",
			Handler:    _KnowledgeBaseQAService_ImportQAPair_Handler,
		},
		{
			MethodName: "GetQAImportTip",
			Handler:    _KnowledgeBaseQAService_GetQAImportTip_Handler,
		},
		{
			MethodName: "ExportQAPair",
			Handler:    _KnowledgeBaseQAService_ExportQAPair_Handler,
		},
		{
			MethodName: "KnowledgeQAHit",
			Handler:    _KnowledgeBaseQAService_KnowledgeQAHit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/knowledgebase-qa-service/knowledgebase-qa-service.proto",
}
